version: "3"

services:
  healthchecker:
    image: hello-world
    depends_on:
      server:
        condition: service_healthy
      postgres:
        condition: service_healthy

  server:
    image: aria3ppp/url-shortener
    # build:
    #   context: .
    #   args:
    #     - GO_VERSION=1.20
    #     - MIGRATE_VERSION=4.15.2
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:${SERVER_PORT} | grep -q 'HTTP/1.1 404 Not Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  postgres:
    image: postgres:14-alpine
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p $${POSTGRES_PORT} -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local