services:
  healthchecker:
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: .
      args:
        - GO_VERSION=1.20
        - MIGRATE_VERSION=4.15.2
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:${SERVER_PORT} | grep -q 'HTTP/1.1 404 Not Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
