version: "3"

services:
  healthchecker:
    image: hello-world
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p $${POSTGRES_PORT} -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 120