// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xW32/bOAz+VwJeH+5wSu1ee0Xqt7tDURxWYEO3PWxBVqg2E6u1JZVSumSB//eBcn44",
	"idMOQdFie4ojiRS/j+RHzSA1pTUatXeQzMBKkiV6pPDP5YY8asyunSelR7ymNCRgpc9BgJYlQrJ9TADh",
	"/VgRZpB4GqMAl+ZYSrYvlb5EPfI5JKeCHXkkdvmlL7vf/ul+jrtngz8PQICf2uC8dllVVe0Vnf/XZApD",
	"gP8RSo+XSt9dLbemvJEa7VF7/pTWFiqVXhkd3TqjA7BlOJaMRfJzf22A9w1YwJgKdjA0VEoPCYxJteBq",
	"ktUPNoPlIXNzi6ln8JWYg/3okJ4HrJXOfTWUrcW4XBRQyskC+Eksmjz02sA6pLoeZo9btjJ43Z7zDW4W",
	"V4hVmK1cBTtnjXbbZVIv/3x18iIMt3QyB9e4u41vARm6lJRl7iCB84ksbYGdRQ44+HMiQ8/EPrIv/tii",
	"qETn5Ahb9jaALg7uC+cCPZdT3YzPAuol+2c/1JUAh+mYlJ++ZxDrcV835SSAZP830ql0FVjuva0vU3po",
	"QpqULzDUfNFdVB91peUOeEBydTBHhzGzbixq3krg+DA+jIMO+DyEERVK3wVWjQvcM7eB+f8zSBoKAM0x",
	"EhJ2QDiEBH6LVqMwWps0UfuY2VSZv+J4t7v5uWiHFFUCTuKjp8232yhYnu1p+fePhNxi2SgFSPqtRdAf",
	"VAM+FxITzTaVpeJ7R9iSqnlrwQa7x3GPf9aL9B1SKTnezhVmijD1nd9xYpEUlqi9LP4AATnKbP6guTR1",
	"N6434hMDugoUn7wCxeOylDSFBD6ZMXUuzj90UGfWKO3Zc/Ot1m+/YXUk2pL2avBIdiLO6FMpYvWDfZpg",
	"l3r+ykQvCH1Mn5aE7qVPmy/DHfq03kFv37ySglS1iNDDgtbwCgoTIomiwqSyyI3zSS/uxVANBEy6zhtb",
	"qFEe+FNM233qj6Q9Hg5P9S0Plu8BAAD//5ArGFvPDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
