// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapi

const (
	Username_passwordScopes = "username_password.Scopes"
)

// ShortenedString defines model for shortened_string.
type ShortenedString = string

// CreateLinkResponseBody defines model for CreateLinkResponseBody.
type CreateLinkResponseBody struct {
	ShortenedString string `json:"shortened_string"`
	Url             string `json:"url"`
	Username        string `json:"username"`
}

// ErrorResponseBody defines model for ErrorResponseBody.
type ErrorResponseBody struct {
	Error   *string `json:"error,omitempty"`
	Message string  `json:"message"`
}

// GetLinkUserResponseBody defines model for GetLinkUserResponseBody.
type GetLinkUserResponseBody struct {
	Username string `json:"username"`
}

// CreateLinkRequestBody defines model for CreateLinkRequestBody.
type CreateLinkRequestBody struct {
	ShortenedString *string `json:"shortened_string,omitempty"`
	Url             string  `json:"url"`
}

// CreateUserRequestBody defines model for CreateUserRequestBody.
type CreateUserRequestBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// CreateLinkJSONBody defines parameters for CreateLink.
type CreateLinkJSONBody struct {
	ShortenedString *string `json:"shortened_string,omitempty"`
	Url             string  `json:"url"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// CreateLinkJSONRequestBody defines body for CreateLink for application/json ContentType.
type CreateLinkJSONRequestBody CreateLinkJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody
